# Use cosine similarity to measure the similarity between sentence & using Tf-idf to vectorize sentences in a document
http://scikit-learn.org/stable/modules/feature_extraction.html
4.2.3.4 explains the Ti-idf feature

Cosine similarity is a measure between two vectors (by calculating the angle between them, instead of just magnitutde of two

The reason that Cosine similarity is very useful for ti-idf feature, is because the vectorized sentence is sparse vector (explanation of sparse vector, see below)

In [124]:
documents = (
"The sky",
"The is blue",
"The sun is bright",
"The sky in shining sum",
"We can see the shining sun, the sun"
)

import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(documents) # vectorize the documents
print tfidf_matrix.shape

from sklearn.metrics.pairwise import cosine_similarity
cos_between_vector1_to_others = cosine_similarity(tfidf_matrix[0:1], tfidf_matrix)

import math
cos_val = cos_between_vector1_to_others[0,2] # cosine angle between vectorized sentence 1 to sentence 3
angle_in_radians = math.acos(cos_val)
print 'the radians of the angle between two vector', math.degrees(angle_in_radians)

(5, 12)
the radians of the angle between two vector 81.2350831717


For the whole documents, the tfidf is calculated based on the total distinct word. if the sentence 1 has 3 distinct word from the whole documents word dictionary, then only those 3 entries in the vector_sentence1 has non-zero values, others will be zeros. Since many entries might be 0's, the tfidf vector is a sparse vector (only small number of dimensions have non-zero values).

And the cosine similarity will be very efficient to be applied to text vectorized vector, sparse vector, because the value will based on calculating dot product between non-zero entries in two vectors, and divide by the product of norm

In [125]:
for i in range(tfidf_matrix.shape[0]):
    print tfidf_matrix[i,:].data

[ 0.861037    0.50854232]
[ 0.72971837  0.58873218  0.34771471]
[ 0.62883263  0.50733821  0.50733821  0.29964212]
[ 0.53233003  0.42948052  0.53233003  0.42948052  0.25365811]
[ 0.37364424  0.37364424  0.37364424  0.30145382  0.60290764  0.35608696]


In [126]:
print cosine_similarity(tfidf_matrix[0,:], tfidf_matrix) #the first sparse vector cosine similarity with other 4 vectors

[[ 1.          0.17682765  0.1523807   0.4987945   0.18108529]]


In [127]:
print cosine_similarity(tfidf_matrix, tfidf_matrix) # confusion matrix all to all cosine similarities

[[ 1.          0.17682765  0.1523807   0.4987945   0.18108529]
 [ 0.17682765  1.          0.40287631  0.08820066  0.12381668]
 [ 0.1523807   0.40287631  1.          0.07600665  0.41257673]
 [ 0.4987945   0.08820066  0.07600665  1.          0.21979289]
 [ 0.18108529  0.12381668  0.41257673  0.21979289  1.        ]]
